name: Market Report Harvester V6

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs automatically every day at 07:00 UTC
  schedule:
    - cron: '0 7 * * *' 

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # CRITICAL: Install Chrome for Selenium using the reliable action
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # Installs the Python libraries
      - name: Install dependencies
        run: pip install -r backend-scraper/requirements.txt

      # Runs the Harvester script
      - name: Run Harvester V6 script
        run: python backend-scraper/harvester.py

      # Commits the newly downloaded reports from the Inbox folder
      - name: Commit new reports
        run: |
          git config --global user.name 'TeaTrade-Harvester-Bot'
          git config --global user.email 'actions@github.com'
          # Check if there are new files in the Inbox
          if [ -n "$(git status Inbox/ --porcelain)" ]; then
            echo "New reports found. Committing..."
            git add Inbox/
            git commit -m "Automated: Harvested new market reports (V6)"
            git push
          else
            echo "No new reports found in Inbox. Skipping commit."
          fi