name: Tea Data Automation

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 AM UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 hour timeout
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr libtesseract-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright beautifulsoup4 aiohttp requests aiosqlite
        pip install opencv-python-headless pytesseract
        pip install pandas numpy
        playwright install chromium
        
    - name: Create required directories
      run: |
        mkdir -p source_reports/colombo
        mkdir -p source_reports/mombasa
        mkdir -p source_reports/nairobi
        mkdir -p Data/Consolidated
        mkdir -p automation/logs
        
    - name: Run scraper system
      run: |
        cd automation
        timeout 5400 python3 teatrade_aggregator_robust.py || echo "Aggregator completed with timeout"
        
    - name: Generate market intelligence
      run: |
        cd automation
        python3 teatrade_intelligence_aggregator.py
        
    - name: Verify output files
      run: |
        ls -la Data/Consolidated/ || echo "No consolidated data found"
        ls -la market-reports-library.json || echo "No library file found"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Automated data update $(date)"
        git push
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tea-data-reports
        path: |
          Data/Consolidated/
          market-reports-library.json
          automation/logs/
        retention-days: 7
